lollatam/lollatam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('search/', include('search.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lollatam/users/urls.py
from django.urls import path

from . import views

app_name='users'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('verify-email/', views.verify_email, name='verify_email'),
]

lollatam/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Make email field unique for the User model.
User._meta.get_field('email')._unique = True

class Profile(models.Model):
    '''
    Model that represents a user profile in the databaseS
    '''
    COUNTRIES = [
        ('AR', 'Argentina'),
        ('BO', 'Bolivia'),
        ('BZ', 'Belice'),
        ('CL', 'Chile'),
        ('CO', 'Colombia'),
        ('CR', 'Costa Rica'),
        ('CU', 'Cuba'),
        ('DM', 'Dominica'),
        ('DO', 'República Dominicana'),
        ('EC', 'Ecuador'),
        ('GU', 'Guatemala'),
        ('HN', 'Honduras'),
        ('HT', 'Haití'),
        ('JM', 'Jamaica'),
        ('MX', 'México'),
        ('NI', 'Nicaragua'),
        ('PA', 'Panamá'),
        ('PE', 'Perú'),
        ('PR', 'Puerto Rico'),
        ('PY', 'Paraguay'),
        ('SV', 'El Salvador'),
        ('UY', 'Uruguay'),
        ('VE', 'Venezuela'),
    ]

    GENDERS = [
        ('H', 'Hombre'),
        ('M', 'Mujer'),
        ('O', 'Otro'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile", null=False, blank=False)
    username = models.CharField(max_length=15, null=False, blank=False)
    country = models.CharField(max_length=2, choices=COUNTRIES, null=False, blank=False)
    desciption = models.TextField(max_length=150, null=True, blank=True)
    gender = models.CharField(max_length=1, null=False, blank=False, choices=GENDERS, default='M')
    image = models.ImageField(upload_to='profile-pictures', default='profile-pictures/default-user-pp.png', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Fields added for email verification functionality.
    verification_token = models.CharField(max_length=64, null=True, blank=True)
    email_verified = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.username}'

class GameAccount(models.Model):
    '''
    Model that represents a game account in the database
    '''
    SERVERS = [
        ('LAN', 'Latinoamérica Norte'),
        ('LAS', 'Latinoamérica Sur'),
    ]
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, default=None, related_name='accounts')
    username = models.CharField(max_length=100, null=False, blank=False)
    server = models.CharField(max_length=3, choices=SERVERS, null=False, blank=False)

    def __str__(self):
        return f'{self.username}'

lollatam/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

from users.models import User

class UserForm(UserCreationForm):
	'''
	Form that uses built-in UserCreationForm to handle user creation
	'''
	username = forms.CharField(max_length=50, required=True,
	widget=forms.TextInput(attrs={
		'placeholder': 'Nombre de usuario', 
		'name': 'username', 
		'type': 'text', 
		'class': 'form-control'
	}))
	first_name = forms.CharField(max_length=50, required=True,
		widget=forms.TextInput(attrs={
            'placeholder': 'Nombre(s)', 
            'name': 'first_name', 
            'type': 'text', 
            'class': 'form-control'
	    }))
	last_name = forms.CharField(max_length=50, required=True,
		widget=forms.TextInput(attrs={
            'placeholder': 'Apellido(s)', 
            'name': 'last_name', 
            'type': 'text', 
            'class': 'form-control'
	    }))
	email = forms.EmailField(required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'Correo electrónico', 
            'name': 'email', 
            'type': 'email', 
            'class': 'form-control'
        }))
	password1 = forms.CharField(max_length=25, required=True,
		widget=forms.PasswordInput(attrs={
		    'placeholder': 'Contraseña', 
            'name': 'password1', 
            'type': 'password', 
            'class': 'form-control'
	    }))
	password2 = forms.CharField(max_length=25, required=True,
		widget=forms.PasswordInput(attrs={
			'placeholder': 'Confirmar contraseña', 
			'name': 'password2', 
			'type': 'password', 
			'class': 'form-control'
		}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2' )

class AuthForm(AuthenticationForm):
	'''
	Form that uses built-in AuthenticationForm to handle user auth
	'''
	username = forms.CharField(max_length=50, required=True,
		widget=forms.TextInput(attrs={
            'placeholder': 'Nombre de usuario', 
            'name': 'username', 
            'type': 'text', 
            'class': 'form-control'
	    }))
	password = forms.CharField(max_length=25, required=True,
		widget=forms.PasswordInput(attrs={
		    'placeholder': 'Contraseña', 
            'name': 'password', 
            'type': 'password', 
            'class': 'form-control'
	    }))

	class Meta:
		model = User
		fields = ('username','password', )

lollatam/users/views.py
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

from users.forms import UserForm, AuthForm
from users.models import Profile

from lollatam.settings import EMAIL_HOST_USER

import secrets


def login_page(request):

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('search:index'))

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('search:index'))
        else:
            return render(request, 'users/login.html', {
                'form': AuthForm(request.POST),
                'error': 'Las credenciales son inválidas.'
            })

    return render(request, 'users/login.html', {
        'form': AuthForm(),
    })

@login_required
def logout_page(request):
        
	logout(request)
	return HttpResponseRedirect(reverse('users:login'))

def signup(request):

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('search:index'))

    context = {}

    if request.method == 'POST':

        form = UserForm(request.POST)

        # Check for form validation including username and email repeated.
        if form.is_valid():
            
            user = form.save()

            # Create a new profile for the user
            profile = Profile(user=user, username=user.username)
            profile.save()

            # Generate a verification token and save it to the profile
            token = secrets.token_hex(32)
            profile.verification_token = token
            profile.save()

            # Send a verification email
            subject = 'Verifica tu correo electrónico'
            message = f'Hola {user.username},\n\nPor favor haz clic en el siguiente enlace para verificar tu correo electrónico:\n\nhttp://{request.get_host()}/users/verify-email/?token={token}'
            from_email = EMAIL_HOST_USER
            recipient_list = [user.email]
            send_mail(subject, message, from_email, recipient_list)

            login(request, user)

            return HttpResponseRedirect(reverse('search:index'))
        else:
            return render(request, 'users/signup.html', {'form': form})

    context['form'] = UserForm()

    return render(request, 'users/signup.html', context)

@login_required
def verify_email(request):

    token = request.GET.get('token')

    if token is not None:

        try:
            profile = Profile.objects.get(verification_token=token)
            profile.email_verified = True
            profile.verification_token = None
            profile.save()
        except Profile.DoesNotExist:
            pass

    return HttpResponseRedirect(reverse('search:index'))

lollatam/users/templates/users/login.html
{% extends 'users/layout.html' %}

{% load static %}

{% block extend_head %}
{% endblock %}

{% block content %}
    <nav class="navbar navbar-dark navbar-expand-md sticky-top py-3" id="mainNav">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="/"><span class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex justify-content-center align-items-center me-2 bs-icon"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-controller">
                        <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1v-1z"></path>
                        <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729c.14.09.266.19.373.297.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466.206.875.34 1.78.364 2.606.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527-1.627 0-2.496.723-3.224 1.527-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.34 2.34 0 0 1 .433-.335.504.504 0 0 1-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a13.748 13.748 0 0 0-.748 2.295 12.351 12.351 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.354 12.354 0 0 0-.339-2.406 13.753 13.753 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27-1.036 0-2.063.091-2.913.27z"></path>
                    </svg></span><span>LoL LATAM</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav mx-auto"></ul><a class="btn btn-primary shadow" role="button" href="{% url 'users:signup' %}">Registrarse</a>
            </div>
        </div>
    </nav>
    <section class="py-5">
        <div class="container py-5">
            <div class="row mb-4 mb-lg-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <p class="fw-bold text-success mb-2">Inicio de sesión</p>
                    <h2 class="fw-bold">Bienvenido de vuelta</h2>
                </div>
            </div>
            {% if error %}
            <div class="row mb-4 mb-lg-5" style="margin:0px !important;">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <div class="alert alert-warning" role="alert" style="margin:16px; float:center; text-align: left;">
                        {{ error }}
                    </div>
                </div>
            </div>
            {% endif %}
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card">
                        <div class="card-body text-center d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary shadow bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg></div>
                            <form action="{% url 'users:login' %}" method="post">
                                {% csrf_token %}
                                <div class="mb-3">{{ form.username }}</div>
                                <div class="mb-3">{{ form.password }}</div>
                                <div class="mb-3"><button class="btn btn-primary shadow d-block w-100" type="submit">Iniciar sesión</button></div>
                                <p class="text-muted">Recuperar contraseña</p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}

    <script src="{% static 'users/assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'users/assets/js/bold-and-dark.js' %}"></script>

{% endblock %}

lollatam/users/templates/users/signup.html
{% extends 'users/layout.html' %}

{% load static %}

{% block extend_head %}
{% endblock %}

{% block content %}

    <nav class="navbar navbar-dark navbar-expand-md sticky-top py-3" id="mainNav">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="/"><span class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex justify-content-center align-items-center me-2 bs-icon"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-controller">
                        <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1zm-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1v-1z"></path>
                        <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729c.14.09.266.19.373.297.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466.206.875.34 1.78.364 2.606.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527-1.627 0-2.496.723-3.224 1.527-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.34 2.34 0 0 1 .433-.335.504.504 0 0 1-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a13.748 13.748 0 0 0-.748 2.295 12.351 12.351 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.354 12.354 0 0 0-.339-2.406 13.753 13.753 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27-1.036 0-2.063.091-2.913.27z"></path>
                    </svg></span><span>LoL LATAM</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav mx-auto"></ul><a class="btn btn-primary shadow" role="button" href="{% url 'users:login' %}">Iniciar sesión</a>
            </div>
        </div>
    </nav>
    <section class="py-5">
        <div class="container py-5">
            <div class="row mb-4 mb-lg-5" style="margin:0px !important;">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <p class="fw-bold text-success mb-2">Registro</p>
                    <h2 class="fw-bold">Bienvenido</h2>
                </div>
            </div>
            {% if form.errors  %}
            <div class="row mb-4 mb-lg-5" style="margin:0px !important;">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <div class="alert alert-warning" role="alert" style="margin:16px; float:center; text-align: left;">
                        {{ form.errors }}
                    </div>
                </div>
            </div>
            {% endif %}
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card">
                        <div class="card-body text-center d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary shadow bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg></div>
                            <form action="{% url 'users:signup' %}" method="post">
                                {% csrf_token %}
                                <div class="mb-3">{{ form.username }}</div>
                                <div class="mb-3">{{ form.first_name }}</div>
                                <div class="mb-3">{{ form.last_name }}</div>
                                <div class="mb-3">{{ form.email }}</div>
                                <div class="mb-3">{{ form.password1 }}</div>
                                <div class="mb-3">{{ form.password2 }}</div>
                                <div class="mb-3"><button class="btn btn-primary shadow d-block w-100" type="submit">Registrarse</button></div>
                                <p class="text-muted">¿Ya tienes una cuenta?&nbsp;<a href="{% url 'users:login' %}">Iniciar sesión</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts %}

    <script src="{% static 'users/assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'users/assets/js/bold-and-dark.js' %}"></script>

{% endblock %}